#!/usr/bin/env bash
#
# popcorn: a small program to offer movie suggestions and manage a movie watchlist

progname="${0##*/}"

# files used for the script
listdir="${HOME}/.local/share/${progname}"

lastwatched="${listdir}/lastwatched.tmp"
listbak="${listdir}/watchlist.bak"
listfile="${listdir}/watchlist"
notwatching="${listdir}/notwatching.tmp"
seenbak="${listdir}/seenlist.bak"
seenfile="${listdir}/seenlist"
sortfile="${listdir}/sortfile.tmp"


add_batch () {
	local addcount
	addcount=0

	while (( "$#" > 0 )); do
		if grep -Fixq "${1}" "${listfile}"; then
			echo "'${1}' is already on your watchlist."
			shift
		else
			echo "${1}" >> "${listfile}"
			(( addcount++ ))
			shift
		fi
	done
	sort "${listfile}" -o "${sortfile}" && mv "${sortfile}" "${listfile}"
	echo "Added ${addcount} movie(s) to your watchlist."
	return
}

cleanup () {
	cat "${notwatching}" >> "${listfile}"
	sort "${listfile}" -o "${sortfile}" && mv "${sortfile}" "${listfile}"
	rm "${notwatching}"
	return
}

# replace this with just a recomendation to use add_batch??
empty_list () {
	clear
	echo "Uh-oh, you don't seem to have any movies on your list."
	echo "Would you like to add some now? [y/n]"
	read -r -p "> "
	case ${REPLY} in
		Y|y|Yes|yes|YES)
			echo "Enter the names of movies you'd like to watch. Press <C-d> when done."
			echo "cat > ${listfile}"
			cat > "${listfile}"
			echo "Your movie list now has $(wc -l < "$listfile") movie(s)."
			;;
		*)
			echo "Bye!"
			exit
			;;
	esac
	return
}

gen_movie () {
	shuf "${listfile}" | head -n 1
	return
}

remove_batch () {
	local rmcount
	rmcount=0

	while (( "$#" > 0 )); do
		if grep -Fixq "${1}" "${listfile}"; then
			sed -i "/^${1}$/d" "${listfile}"
			(( rmcount++ ))
			shift
		else
			echo "'${1}' is not on your watchlist."
			shift
		fi
	done
	echo "Removed ${rmcount} movie(s) from your watchlist."
	return
}

reselect () {
	sed -i "/^${movie_candidate}$/d" "${listfile}"
	echo "${movie_candidate}" >> "${notwatching}"
	return
}

reset () {
	# uses 1,2,3,4 instead of the letters used elsewhere. Change?
	echo "Which file would you like to reset?
1. Watchlist at ${listfile}
2. Seenlist at ${seenfile}
3. Both
4. Quit"
	read -r -p "> "
	case "${REPLY}" in
		1)
			echo "Are you sure? This action cannot be undone. [y/n]"
			read -r -p "> "
			case "${REPLY}" in
				Y|y|Yes|YES|yes)
					: > "${listfile}"
					echo "Cleared your watchlist."
					;;
				*)
					echo "Changed nothing. Consider backing up your files with '${progname} backup'."
					exit
					;;
			esac
			;;
		2)
			echo "Are you sure? This action cannot be undone. [y/n]"
			read -r -p "> "
			case "${REPLY}" in
				Y|y|Yes|YES|yes)
					: > "${seenfile}"
					echo "Cleared your seenlist."
					;;
				*)
					echo "Changed nothing. Consider backing up your files with '${progname} backup'."
					exit
					;;
			esac
			;;
		3)  
			echo "Are you sure? This action cannot be undone. [y/n]"
			read -r -p "> "
			case "${REPLY}" in
				Y|y|Yes|YES|yes)
					: > "${listfile}"
					: > "${seenfile}" 
					echo "Cleared both your watchlist and seenlist."
					;;
				*)
					echo "Changed nothing. Consider backing up your files with '${progname} backup'."
					exit
					;;
			esac
			;;
		*)
			echo "Changed nothing."
			exit
			;;
	esac
	rm "${lastwatched}"
}

search_batch () {
	while (( "$#" > 0 )); do
		if grep -Fixq "${1}" "${listfile}"; then
			echo "'${1}' is on your watchlist. Would you like to remove it? [y/n]"
			read -r -p "> "
			case "${REPLY}" in
				Y|y|Yes|YES|yes)
					sed -i "/^${1}$/d" "${listfile}"
					echo "Removed '${1}' from your watchlist."
					;;
				*)
					;;
			esac
		else
			echo "'${1}' is not on your list. Would you like to add it? [y/n]"
			read -r -p "> "
			case "${REPLY}" in
				Y|y|Yes|YES|yes)
					echo "${1}" >> "${listfile}"
					echo "Added '${1}' to your watchlist."
					;;
				*)
					;;
			esac
		fi
		shift
	done
	sort "${listfile}" -o "${sortfile}" && mv "${sortfile}" "${listfile}"
	return
}

update_list () {
	sed -i "/^${movie_last}$/d" "${listfile}"
	# do something better with this?
	echo "${movie_last} on $(date +%D)" >> "${seenfile}"
	sort "${seenfile}" -o "${sortfile}" && mv "${sortfile}" "${seenfile}"
	return
}

usage () {
	# is there a better way to format this?
	cat <<- EOF

	${progname}: Interactive program to manage a movie watchlist

	Usage: 

	  ${progname} [command]

	  When no command is given, ${progname} functions in interactive mode.

	Commands:

	  add "Movie Title"      Add one or more movies to your watchlist. Place each title within
                         its own set of quotes.
	  backup                 Create a backup of your lists
	  count                  Display the amount of movies in your watchlist
	  help                   Display program use information
	  list                   List the contents of your watchlist
	  remove "Movie Title"   Remove one or more movies from your watchlist. Place each title within
                         its own set of quotes.
	  reset                  Clear either the watchlist, seenlist, or both
	  restore                Restore your lists from backup
	  search "Movie Title"   Search your watchlist for one or more movies. Place each title within
                         its own set of quotes.
	  seen                   List the contents of your seenlist
	  watched "Movie Title"  Remove one or more movies from your watchlist and place them on your
                         seenlist. Place each title within its own set of quotes. If a movie is not
                         on your watchlist, it will still be added to your seenlist.
	  version                Print version number

	EOF
	return
}

watched_batch () {
	local addcount rmcount
	addcount=0
	rmcount=0

	while (( "$#" > 0 )); do
		echo "${1} on $(date +%D)" >> "${seenfile}"
		(( addcount++ ))
		if grep -Fixq "${1}" "${listfile}"; then
			sed -i "/^${1}$/d" "${listfile}"
			(( rmcount++ ))
		fi
		shift
	done
	sort "${seenfile}" -o "${sortfile}" && mv "${sortfile}" "${seenfile}"
	echo "Removed ${rmcount} movie(s) from your watchlist, and added ${addcount} movie(s) to your seenlist."
	return
}


# check for the existance of the files and directories needed in the script
if [[ ! -e "${listdir}" ]]; then
	mkdir "${listdir}"
fi

if [[ ! -e "${listfile}" ]]; then
	touch "${listfile}"
fi

if [[ ! -e "${seenfile}" ]]; then
	touch "${seenfile}"
fi


# process command line options
while [[ -n "${1}" ]]; do
	case "${1}" in
		add)
			shift
			add_batch "$@"
			exit
			;;
		# should the backup process be automatic? 
		backup)
			cp "${listfile}" "${listbak}"
			cp "${seenfile}" "${seenbak}"
			echo "Watchlist and seenlist backed up."
			exit
			;;
		count)
			echo "Your movie list has $(wc -l < "$listfile" ) movie(s)."
			exit
			;;
		help|--help)
			usage
			exit
			;;
		list)
			cat "${listfile}"
			exit
			;;
		remove)
			shift
			remove_batch "$@"
			exit
			;;
		reset)
			reset
			# deliberately not exiting so that it moves to empty_list
			;;
		# is this really needed?
		restore)
			cat "${listbak}" > "${listfile}"
			cat "${seenbak}" > "${seenfile}"
			echo "Watchlist and seenlist restored from backups."
			exit
			;;
		search)
			shift
			search_batch "$@"
			exit
			;;
		seen)
			cat "${seenfile}"
			exit
			;;
		watched)
			shift
			watched_batch "$@"
			exit
			;;
		version|--version)
			printf '%s 0.1.2\n' "${progname}"
			exit
			;;
		*)
			echo "Bad usage. Try '${progname} help' for more information." >&2
			exit 1
			;;
	esac
	shift
done


# check to see if you watched the movie you chose last time the program was run
if [[ -e "${lastwatched}" ]]; then

	movie_last="$(< "${lastwatched}")"

	clear
	echo "Did you end up watching '${movie_last}'? [y/n/q]"
	read -r -p "> "
	case "${REPLY}" in
		Y|y|Yes|yes|YES)
			update_list
			echo "Updated your watchlist and seenlist."
			rm "${lastwatched}"
			exit
			;;
		Q|q|quit|Quit|QUIT)
			echo "Bye!"
			exit
			;;
		*)
			echo "Okay, would you like to watch a different movie?"
			read -r -p "> "
			case "${REPLY}" in
				Y|y|Yes|yes|YES)
					rm "${lastwatched}"
					;;
				*)
					echo "Bye!"
					exit
					;;
			esac
			;;
	esac
fi



# if an empty movie list is encountered
if [[ ! -s "${listfile}" ]]; then
	empty_list
	echo "Would you like to pick a movie now?"
	read -r -p "> "
	case "${REPLY}" in
		Y|y|Yes|yes|YES)
			;;
		*)
			sort "${listfile}" > "${sortfile}" && mv "${sortfile}" "${listfile}"
			echo "Bye!"
			exit
			;;
	esac
fi


# pick a random movie from your list and offer it
#
# there MUST be a better way to do this, perhaps with 
# sort -R "$listfile" | while read; do
#	for i in $REPLY; do
clear
echo "Picking a movie for you..."
while true; do
	if [[ -s "${listfile}" ]]; then
		movie_candidate="$(gen_movie)"
		echo "Would you like to watch '${movie_candidate}'? [y/n/q]"
		read -r -p "> "
		case "${REPLY}" in
			Y|y|Yes|yes|YES)
				echo "Great! I'll ask you how it went later."
				echo "${movie_candidate}" > "${lastwatched}"
				if [[ -e "${notwatching}" ]]; then
					cleanup
				fi
				exit
				;;
			Q|q|quit|Quit|QUIT)
				echo "Bye!"
				if [[ -e "${notwatching}" ]]; then
					cleanup
				fi
				exit
				;;
			*)
				reselect
				continue
				;;
		esac
	else
		echo "There are no more movies on your list. Do you want to go through it again?"
		read -r -p "> "
		case "${REPLY}" in 
			Y|y|Yes|YES|yes)
				cleanup
				continue 2
				;;
			*)
				cleanup
				echo "Bye!"
				exit
				;;
		esac
	fi
done
